/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotify1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ubuntu
 */

public class Spotify extends javax.swing.JFrame {
    
     public Lista salsa = new Lista();
     public Lista rock = new Lista();
    public Lista general = new Lista();
    
     
     DefaultTableModel modeloSalsa; 
     DefaultTableModel modeloGeneral;
     DefaultTableModel modeloRock;
     
        
     
    /**
     * Creates new form spotify1
     */
    public Spotify() {
        modeloRock = new DefaultTableModel();
        modeloRock.addColumn("ROCK");
        
        
        modeloGeneral = new DefaultTableModel();
        modeloGeneral.addColumn("General");
        
        
        modeloSalsa= new DefaultTableModel();
        modeloSalsa.addColumn("SALSA");
        initComponents();
        
    }
    
    public void BorrarTextfield(){
        jTextFieldCancion.setText("");
    }
 
    
    
    public void ActualizarTablaSalsa(){
        //Sección 1 
       
        //Sección 2

        String [] fila=new String[1]; 

        //Sección 3
        if(this.salsa!=null){
            salsa.irNodoSiguiente();
            Nodo auxiliar;
            auxiliar = salsa.primero;
            
            while(auxiliar!=null){
            fila[0]=auxiliar.Cancion;
            
         //Sección 4

         this.modeloSalsa.addRow(fila); 
        auxiliar = auxiliar.siguiente;
            }  
        }
         
         
        //Sección 5

        this.tblSalsa.setModel(modeloSalsa); 
}
    
    public void ActualizarTablaGeneral(){
       
        String [] fila=new String[1]; 

        //Sección 3
        if(this.general!=null){
            general.irNodoSiguiente();
            Nodo auxiliar;
            auxiliar = general.primero;
            
            while(auxiliar!=null){
            fila[0]=auxiliar.Cancion;
            
         //Sección 4

         this.modeloGeneral.addRow(fila); 
        auxiliar = auxiliar.siguiente;
            }  
        }
         
         
        //Sección 5

        this.tblGeneral.setModel(modeloGeneral); 
    }
    
    public void ActualizarTablaRock(){
        
        
        //Sección 2

        String [] fila=new String[1]; 

        //Sección 3
        if(this.rock!=null){
            rock.irNodoSiguiente();
            Nodo auxiliar;
            auxiliar = rock.primero;
            
            while(auxiliar!=null){
            fila[0]=auxiliar.Cancion;
            
         //Sección 4

         this.modeloRock.addRow(fila); 
        auxiliar = auxiliar.siguiente;
            }  
        }
         
         
        //Sección 5

        this.tblRock.setModel(modeloRock); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        btnAgrupado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCancion = new javax.swing.JTextField();
        chSalsa = new javax.swing.JRadioButton();
        chRock = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRock = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSalsa = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGeneral = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("canción ");

        chSalsa.setSelected(true);
        chSalsa.setText("Salsa");
        chSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSalsaActionPerformed(evt);
            }
        });

        chRock.setText("Rock");
        chRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chRockActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblRock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRock);
        if (tblRock.getColumnModel().getColumnCount() > 0) {
            tblRock.getColumnModel().getColumn(0).setHeaderValue("ROCK");
        }

        tblSalsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SALSA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSalsa);
        if (tblSalsa.getColumnModel().getColumnCount() > 0) {
            tblSalsa.getColumnModel().getColumn(0).setHeaderValue("SALSA");
        }

        tblGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GENERAL"
            }
        ));
        jScrollPane3.setViewportView(tblGeneral);
        if (tblGeneral.getColumnModel().getColumnCount() > 0) {
            tblGeneral.getColumnModel().getColumn(0).setHeaderValue("GENERAL");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(jTextFieldCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chSalsa)
                        .addGap(44, 44, 44)
                        .addComponent(chRock)
                        .addGap(50, 50, 50)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chSalsa)
                    .addComponent(chRock)
                    .addComponent(btnAgregar))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // aqui
        btnAgrupado.add(chRock);
        btnAgrupado.add(chSalsa);
        
        if(jTextFieldCancion.getText().length()>0){
            if(chRock.isSelected()){
                this.general.insertar(jTextFieldCancion.getText(), 2);
                this.rock.insertar(jTextFieldCancion.getText(),2);
                ActualizarTablaRock();
               
                ActualizarTablaGeneral();
                
                BorrarTextfield();
                
            }else if(chSalsa.isSelected()){
                
                this.general.insertar(jTextFieldCancion.getText(), 0);
                this.salsa.insertar(jTextFieldCancion.getText(),0);
                BorrarTextfield();
                ActualizarTablaSalsa();
                ActualizarTablaGeneral();
             
            }else{
            JOptionPane.showMessageDialog(null, "Por favor elegir genero de la canción ");
            
        }
           
        }else{
            
            JOptionPane.showMessageDialog(null, "Por favor ingresar nombre de la canción ");
            
        }
            
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void chRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chRockActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_chRockActionPerformed

    private void chSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSalsaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_chSalsaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spotify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup btnAgrupado;
    private javax.swing.JRadioButton chRock;
    private javax.swing.JRadioButton chSalsa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldCancion;
    private javax.swing.JTable tblGeneral;
    private javax.swing.JTable tblRock;
    private javax.swing.JTable tblSalsa;
    // End of variables declaration//GEN-END:variables
}
